### ISSUE TITLE
SQL Execution Support

### ISSUE THREAD

**Issue by cboebel** [rgbkrk/atom-script#115]
Is anyone working on executing sql scripts? If this is not already in the works, I can do so.

**Comment by MrTrustworthy** [comment]
Piggybacking on this thread since it seems to be main/original SQL discussion:

It is currently possible to run a file with SQL commands by creating a "Script: Run Options" profile containing (PostgreSQL as example, assuming passwords are set accordingly):

Command: psql
Command Arguments: -h <server> -U <user> -d <database> -f {FILE_ACTIVE}

While a better way to input the login data would be great, this current state is sufficient for most use cases (at least for me).

HOWEVER: Since atom-script does not support SQL, running with this "Run Option" fails due to "Command not configured for SQL". The workaround is to set the language of the current buffer (CTRL+SHIFT+L on Windows) to a supported language (for example C). This, in turn, ruins syntax highlighting, toggle-comment etc. and consequently forces me to switch between SQL, C and back to SQL quite often.

Enabling support for SQL files and maybe adding some helpful information in the readme/when running SQL files would go a long way to make atom-script useable for SQL in general.

**Comment by rgbkrk** [comment]
@MrTrustworthy thanks for outlining a solution. Want to create a dummy runner that runs e.g. `echo "SQL requires setting Script: Run Options directly"`?

**Comment by MrTrustworthy** [comment]
Sure! I'll send a pull request once I'm done.
