### ISSUE TITLE
Bug: does not escape HTML/XML output

### ISSUE THREAD

**Issue by caleb531** [rgbkrk/atom-script#261]
Hi,

Atom Script seemingly can't handle HTML/XML output. Because Atom itself is web-based, the HTML/XML becomes parsed into the DOM, when it should outputted as raw text. This is especially annoying in languages such as Python, where strings in the form of `<foo object at 0x1066e9240>` may be outputted to the console.

I presume that the solution to this bug is to escape reserved HTML/XML characters *before* displaying them in the output viewer.
![HTML/XML output FAIL](https://cloud.githubusercontent.com/assets/872474/5593800/fb338eac-91dc-11e4-84ec-8594f2b239f6.png)

Thanks,
Caleb

**Comment by erran** [comment]
@caleb531 this is related to an option we added. If you open the Script prefences and ensure the "Escape Console Output" option is set to true (this should be the default, if not this is the root cause of the issue).

In terms of strings like `<foo object at 0x1066e9240>` being in the output, that example and other examples I can think of (Ruby) are usually debug level logging in scripts. If the script being run doesn't print HTML w/ the respecitve escape codes then the script should be ran with the escape output option set to true.

**Comment by caleb531** [comment]
That option works perfectly if I set it to `'escapeConsoleOutput': true` in `config.cson`, because I could not find it in Script preferences. I am using the latest version of Script—what am I missing?

![Script preferences](https://cloud.githubusercontent.com/assets/872474/5594084/fb10381a-91ed-11e4-9ec8-7e3e7c20e9d0.png)

Thanks, @erran.
Caleb

**Comment by erran** [comment]
@caleb531 this bug is actually a duplicate of #238 it seems, at first I was confused by the screenshot since that is the purpose of the feature. Fixed by #242. I'll publish the release now.

**Comment by caleb531** [comment]
Fantastic—thanks very much for your quick and helpful answer. :)

Caleb

**Comment by erran** [comment]
@caleb531 thanks for bringing the issue up. The fix should've been published sooner. Shipped.

```
aus-mac-1033 @ ~/g/atom-script (master) λ apm publish minor
Preparing and tagging a new version ✓
Pushing v2.16.0 tag ✓
Publishing script@v2.16.0 ✓
```
