### ISSUE TITLE
Error When Running javascript code( via ctrl-shift-b)

### ISSUE THREAD

**Issue by PedroCastanedaOne** [rgbkrk/atom-script#271]
'node' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.043s]

**Comment by rgbkrk** [comment]
Make sure to launch Atom from the console/terminal. This gives atom all your useful environment variables. If Atom can't find it, it's because it's not on the `PATH` to Atom.

If you *really* wish to open atom from a launcher/icon, see [this issue for a variety of workarounds that have been suggested](https://github.com/rgbkrk/atom-script/issues/61#issuecomment-37337827).
