### ISSUE TITLE
Add support for GitHub Markdown

### ISSUE THREAD

**Issue by adamabernathy** [rgbkrk/atom-script#582]
Could this happen?

**Comment by rgbkrk** [comment]
It would be really cool if we could run the code within code fence blocks.

**Comment by fasiha** [comment]
I’d love it if I could just configure script to run `node` (or `python` or whatever) on a session-by-session basis to send selected code snippets from Markdown to node/python. I’m trying to do so via `configure run options` but I get “Command not configured for GitHub Markdown!”.

**Comment by rgbkrk** [comment]
If you want to keep a running session, use [Hydrogen](https://github.com/nteract/hydrogen)

**Comment by Aisuko** [comment]
Same problem with you @fasiha

**Comment by fasiha** [comment]
@Aisuko if you’re working with a system that supports Jupyter (JS, Python, Torch/Lua, etc.), hugely recommend checking out Hydrogen. I wrote a very small plugin that helps me select fenced code-blocks and send them to Hydrogen/Jupyter, which prints the result in Atom. (I then have a little script that, outside of Atom, will evaluate all fenced code blocks and format the result and insert them into the Markdown, but that’s very customized for each file/system.)

I completely forgot about atom-script. It might be really useful to do this kind of workflow in atom-script also because not everything I use has a Jupyter plugin (like, ugh, Matlab).
