### ISSUE TITLE
Not support print chinese

### ISSUE THREAD

**Issue by ld000** [rgbkrk/atom-script#738]
I have a python file like

``` python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

print('测试')
```

and print like this

```
����
```

**Comment by SamStrawbridge** [comment]
what OS / Version of script are you using?  works ok on OSX with 3.4.0, quick thing just to check, have a look at your file encoding settings for atom, playing with this and also changing the encoding on the bottom right of the editor caused some really weird behaviour for me.

**Comment by LD00000** [comment]
OS: WIN10
script Version: 3.4.0
My atom file encoding setting and bottom right encoding are both utf-8
It works ok in windows cmd, but not work well in script

**Comment by dbolton** [comment]
@LD00000 I came across the same problem. For me, it looks like atom-script on Windows uses cp1252 (Windows 1252) encoding by default instead of utf-8 (the default encoding may depend on your locale and platform).

As a work-around you can specify the encoding as utf-8 in your code for the system out and error streams:

```
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')

print ('测试')
```

**Comment by Nick-Seong** [comment]
so much thanks @dbolton

**Comment by wanghe826** [comment]
so much thanks @dbolton

**Comment by github-mi** [comment]
I solved this problem by adding an environment varibale 

> PYTHONIOENCODING=utf-8

You can press Ctrl+Alt+Shift+O to add it.
