### ISSUE TITLE
script installation error on windows 10

### ISSUE THREAD

**Issue by viyatgandhi** [rgbkrk/atom-script#815]
getting below error while installing script - started atom from command line with admin rights
Windows 10 
atom version : 1.5.3

command used to install : apm install script

tried to solve tar.unpack untar error but no success 
npm cache clean didn't work

below is the error msg

Thanks in advance

```
npm ERR! tar.unpack untar error C:\Users\viyat\.atom\.apm\karg\0.2.1\package.tgz
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\viyat\\AppData\\Local\\atom\\app-1.5.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\viyat\\AppData\\Local\\atom\\app-1.5.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\viyat\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\viyat\\.atom\\.apmrc" "install" "C:\\Users\\viyat\\AppData\\Local\\Temp\\d-116125-6784-n1fhg3\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path C:\Users\viyat\AppData\Local\Temp\apm-install-dir-116125-6784-f7s76x\node_modules\script\node_modules\ansi-to-html\node_modules\karg\Icon
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open 'C:\Users\viyat\AppData\Local\Temp\apm-install-dir-116125-6784-f7s76x\node_modules\script\node_modules\ansi-to-html\node_modules\karg\Icon
'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by hellbe** [comment]
+1 same error here on Win 7 x64

**Comment by antmay** [comment]
I am also getting the same error on a newly installed Windows 10

**Comment by zaha** [comment]
Same here, Win 10

**Comment by viyatgandhi** [comment]
@rgbkrk can you please let us know the issue or workaround for this problem ? too many people are facing this issue... Thanks in advance

**Comment by rgbkrk** [comment]
Hopefully I can try installing this on a Windows VM soon. Otherwise, we're always open to people debugging this and finding out a solution if I'm not fast enough.

**Comment by dhh-hss** [comment]
I tried myself on a freshly installed **Windows 10** today. It worked fine for me, as long as I had **Git** installed. (Since **script** relies on **Git** being installed to get some dependencies.)

**Comment by rgbkrk** [comment]
> Since script relies on Git being installed to get some dependencies

I didn't realize that was going to be an unsafe assumption, thanks for bringing that up. We need to get off of that setup then (or provide an escape hatch so people don't need `git`).

**Comment by viyatgandhi** [comment]
@dhh-hss I have Git installed on my pc still getting the error... do need to setup some path variable for Git so that script installation can use it ?

**Comment by dhh-hss** [comment]
@rgbkrk I tested it out with `apm install script --verbose`. To get some better messages. I'm not entirely sure, but it seems to fail on some kind of **node** package. It throws the error, that you need **Git**. (It actually recommends to install the **GitHub** app.) And then it returns to the prompt without installing **script**.

@viyatgandhi Yes, for **Git** to function in almost any case. (Especially on **Windows**.) You'll need it in your **PATH** variable. If you download **Git** from http://git-scm.com/ - the installer can take care of that. You just have to choose the setting. **Mac OS X** comes with **Git**, although being an older version out of the box. If you have installed **Xcode** or used the **Xcode tools** before. On **Mac OS X**, I use **homebrew** though, to keep my packages up to date. (`brew install git`)

**Comment by viyatgandhi** [comment]
@dhh-hss Thanks for the info!!! Script is installed successfully after setting Git path in PATH variable on windows 10. I will spread the word for win 10 users so that others can install too.

**Comment by karottc** [comment]
This is new problem: 

error message is below:

npm ERR! Command failed: Cloning into bare repository 'C:\Users\karottc\.atom\
apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

------------------

I hava already installed git and set PATH variable.

**Comment by DemersM** [comment]
same problem than @karottc here

**Comment by senseoki** [comment]
same problem.

Installing “script@3.6.3” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\Administrator\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\Administrator\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Administrator\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\Administrator\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\Administrator\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Administrator\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\Administrator\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Administrator\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.252.121]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.7.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.7.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Administrator\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Administrator\\.atom\\.apmrc" "install" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\d-116315-10000-1sxtlq3\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Administrator\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.121]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by dhhdev** [comment]
> npm ERR! Command failed: Cloning into bare repository 'C:\Users\Administrator.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...

@senseoki You need to properly install Git. That's the error you get, it couldn't clone into a bare repository.

**Comment by DemersM** [comment]
@dhhdev Git is properly installed. I have the same error when I tryed to install this package mannualy after cloned this package to a local directory.

**Comment by DemersM** [comment]
The problem is triggered during the installation of node-simple-plist. This library is deprecated in favor to lodash. Why is it still in atom-script dependancy list?

**Comment by DemersM** [comment]
https://github.com/rgbkrk/atom-script/issues/881

**Comment by sanjeev45** [comment]
Installing “script@3.8.1” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\Sanjib\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\Sanjib\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Sanjib\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\Sanjib\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\Sanjib\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Sanjib\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\Sanjib\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Sanjib\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.253.113]: errno=Invalid argument
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Sanjib\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Sanjib\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Sanjib\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Sanjib\\.atom\\.apmrc" "install" "C:\\Users\\Sanjib\\AppData\\Local\\Temp\\d-116614-11524-zry6v8\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Sanjib\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Invalid argument
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by Akumetsu-Dev** [comment]
npm ERR! git clone C:\Users\Walddys Emmanuel\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\WALDDY~1\AppData\Local\Temp\npm-6476-ce08451a\git-cache-b4a93e876c07\5ff35d61ff600391ccd784a18616fa73c09e0aea: Cloning into 'C:\Users\WALDDY~1\AppData\Local\Temp\npm-6476-ce08451a\git-cache-b4a93e876c07\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! git clone C:\Users\Walddys Emmanuel\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\WALDDY~1\AppData\Local\Temp\npm-6476-ce08451a\git-cache-b4a93e876c07\5ff35d61ff600391ccd784a18616fa73c09e0aea: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Walddys Emmanuel\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\WALDDY~1\AppData\Local\Temp\npm-6476-ce08451a\git-cache-b4a93e876c07\5ff35d61ff600391ccd784a18616fa73c09e0aea: fatal: unable to fork
npm ERR! git clone C:\Users\Walddys Emmanuel\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\WALDDY~1\AppData\Local\Temp\npm-6476-ce08451a\git-cache-b4a93e876c07\5ff35d61ff600391ccd784a18616fa73c09e0aea: 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Walddys Emmanuel\\AppData\\Local\\atom\\app-1.9.6\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Walddys Emmanuel\\AppData\\Local\\atom\\app-1.9.6\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Walddys Emmanuel\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Walddys Emmanuel\\.atom\\.apmrc" "install" "C:\\Users\\WALDDY~1\\AppData\\Local\\Temp\\d-11677-6464-mzklh2\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\WALDDY~1\AppData\Local\Temp\npm-6476-ce08451a\git-cache-b4a93e876c07\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
