### ISSUE TITLE
Add support for MATLAB

### ISSUE THREAD

**Issue by snakecy** [rgbkrk/atom-script#953]
Sometimes, I want to run the matlab code atom, so is there any easy way to finish this part?

**Comment by nixel2007** [comment]
Matlab support was added in last release. Try it out

**Comment by chris-hld** [comment]
Currently the '-nojvm' option doesn't allow to generate plots at all. I would highly recommend to remove this flag, or is there a specific reason for it?

**Comment by chris-hld** [comment]
This should also solve #975 
https://github.com/rgbkrk/atom-script/issues/975

**Comment by bremme** [comment]
The reason I put the `-nojvm` and `-nodisplay` options in there is because I wasn't able to solve some problems related to using MATLAB's graphical capabilities. Other than that, it also improves the speed of running MATLAB scripts.

When running MATLAB scripts using the Atom script package you want that the MATLAB interperter exits cleanly after running your script. If the interperter does not exit, you will end up with one (zombie) MATLAB process every time you run a script.

The way I implemented this, as you can see in grammars.coffee is: run the script catch and display errors and either `exit(0)` or `exit(1)` if an error occures.

If you would just remove the the `-nojvm` and `-nodisplay` options, you would be able to open a plot window for example, but this window would close right away because of the `exit(1)` and `exit(0)` calls.

If you would remove those as well, your plot window would stay open. But when closing the window, the MATLAB process does not exit, this is a problem.

A possible way to fix this would be to inject additional MATLAB code which monitors open windows and closes MATLAB if all windows are closed?

Update, I think I found a solution:). If A change the grammars.coffee file like this it should work:

```coffee
MATLAB:
  "Selection Based":
    command: "matlab"
    args: (context) ->
      code = context.getCode()
      tmpFile = GrammarUtils.MATLAB.createTempFileWithCode(code)
      ['-nodesktop','-nosplash','-r',"try, run('" + tmpFile + "');while ~isempty(get(0,'Children')); pause(0.1); end; catch ME; disp(ME.message); exit(1); end; exit(0);"]
  "File Based":
    command: "matlab"
    args: (context) -> ['-nodesktop','-nosplash','-r',"try run('" + context.filepath + "');while ~isempty(get(0,'Children')); pause(0.1); end; catch ME; disp(ME.message); exit(1); end; exit(0);"]
```

I injected a while loop which monitors the number of children/graphical objects on the root object in addition to catching errors. Now if you create MATLAB windows, you windows will stay open. And when you close them MATLAB will cleanly exit.

I will create a pull request tonight.

**Comment by bremme** [comment]
Created a pull request  #995.

**Comment by nixel2007** [comment]
:ship: 3.9.0
